### ISSUE TITLE
tkinter not installed

### ISSUE THREAD

**Issue by IbrahimElk** [TissueEngineeringLab/MyoFInDer#3]
after following the instructions for the installation in ubuntu 22.04 , it seems that tkinter was not installed. After checking requirements.txt, it also doesn't seem to be included? 

```
$ python3 -c "import myofinder; print(myofinder.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ibrahim/Documents/venv/lib/python3.10/site-packages/myofinder/__init__.py", line 3, in <module>
    from .main_window import Main_window
  File "/home/ibrahim/Documents/venv/lib/python3.10/site-packages/myofinder/main_window.py", line 3, in <module>
    from tkinter import ttk, filedialog, Tk, IntVar, PhotoImage, Menu, StringVar, \
ModuleNotFoundError: No module named 'tkinter'
```

**Comment by IbrahimElk** [comment]
tkinter is a standard library module that comes bundled with Python, it is on my side
